from .consultation_duration import ConsultationDuration
from .consultation_record_exame import ConsultationRecordExame
from .consultation_record import ConsultationRecord
from .consultation import Consultation
from .contract_doctor import ContractDoctor
from .contract_type import ContractType
from .doctor_address import DoctorAddress
from .doctor_day import DoctorDay
from .doctor_speciality import DoctorSpeciality
from .doctor import Doctor
from .exame_type import ExameType
from .exame import Exame
from .laboratory import Laboratory
from .measure import Measure
from .medical_record import MedicalRecord
from .medicine import Medicine
from .patient_address import PatientAddress
from .patient import Patient
from .recepcionist_address import RecepcionistAddress
from .recepcionist import Recepcionist
from .recipe import MedicalRecipe
from .speciality import Speciality
from .uf import UF
from .week_day import WeekDay