INSERT INTO week_day (id, day)
VALUES 
    (0, 'Sunday'),
    (1, 'Monday'),
    (2, 'Tuesday'),
    (3, 'Wednesday'),
    (4, 'Thursday'),
    (5, 'Friday'),
    (6, 'Saturday');

INSERT INTO exame_type (type_exame)
VALUES
    ('Hemograma Completo'),
    ('Hematócrito'),
    ('Hemoglobina'),
    ('Contagem de Plaquetas'),
    ('VHS (Velocidade de Hemossedimentação)'),
    ('Glicemia em Jejum'),
    ('Glicemia Pós-Prandial'),
    ('Hemoglobina Glicada (HbA1c)'),
    ('Curva Glicêmica'),
    ('Colesterol Total'),
    ('HDL'),
    ('LDL'),
    ('VLDL'),
    ('Triglicerídeos'),
    ('Creatinina'),
    ('Ureia'),
    ('Ácido Úrico'),
    ('Clearance de Creatinina'),
    ('TGO (AST)'),
    ('TGP (ALT)'),
    ('Gama GT (GGT)'),
    ('Fosfatase Alcalina'),
    ('Bilirrubina Total'),
    ('Bilirrubina Direta'),
    ('Bilirrubina Indireta'),
    ('Albumina'),
    ('Sódio'),
    ('Potássio'),
    ('Cálcio'),
    ('Magnésio'),
    ('Cloro'),
    ('Fósforo'),
    ('TSH'),
    ('T3'),
    ('T4 Livre'),
    ('Cortisol'),
    ('Insulina'),
    ('Testosterona'),
    ('Estradiol'),
    ('Progesterona'),
    ('Prolactina'),
    ('FSH'),
    ('LH'),
    ('Vitamina D'),
    ('Vitamina B12'),
    ('Ácido Fólico'),
    ('Ferritina'),
    ('TP (Tempo de Protrombina)'),
    ('INR'),
    ('TTPA'),
    ('Fibrinogênio'),
    ('Urina Tipo I (EAS)'),
    ('Urocultura'),
    ('Parasitológico de Fezes'),
    ('Pesquisa de Sangue Oculto nas Fezes'),
    ('Coprocultura'),
    ('HIV'),
    ('Hepatite A'),
    ('Hepatite B'),
    ('Hepatite C'),
    ('Sífilis (VDRL)'),
    ('Dengue'),
    ('COVID-19'),
    ('Chikungunya'),
    ('Zika'),
    ('Toxoplasmose'),
    ('Rubéola'),
    ('Eletrocardiograma (ECG)'),
    ('Ecocardiograma'),
    ('Holter 24h'),
    ('MAPA 24h'),
    ('Teste Ergométrico'),
    ('Radiografia'),
    ('Ultrassonografia'),
    ('Mamografia'),
    ('Tomografia Computadorizada'),
    ('Ressonância Magnética'),
    ('Densitometria Óssea'),
    ('Endoscopia Digestiva Alta'),
    ('Colonoscopia'),
    ('Retossigmoidoscopia'),
    ('Broncoscopia'),
    ('Papanicolau'),
    ('Colposcopia'),
    ('Ultrassom Transvaginal'),
    ('Ultrassom Obstétrico'),
    ('Espirometria'),
    ('Gasometria Arterial'),
    ('Fundoscopia'),
    ('Tonometria'),
    ('Campimetria'),
    ('Eletroencefalograma (EEG)'),
    ('Eletroneuromiografia (ENMG)');

INSERT INTO laboratory (laboratory_name)
VALUES
    ('A+ Medicina Diagnóstica'),
    ('Alta Diagnósticos'),
    ('Biofast'),
    ('Delboni Auriemo'),
    ('Fleury Medicina e Saúde'),
    ('Hermes Pardini'),
    ('Laboratório São Marcos'),
    ('Lavoisier'),
    ('Sabin Medicina Diagnóstica'),
    ('Salomão Zoppi Diagnósticos'),
    ('Unilabs'),
    ('DB Diagnósticos');

INSERT INTO uf (name, abbreviation)
VALUES
    ('Acre', 'AC'),
    ('Alagoas', 'AL'),
    ('Amapá', 'AP'),
    ('Amazonas', 'AM'),
    ('Bahia', 'BA'),
    ('Ceará', 'CE'),
    ('Distrito Federal', 'DF'),
    ('Espírito Santo', 'ES'),
    ('Goiás', 'GO'),
    ('Maranhão', 'MA'),
    ('Mato Grosso', 'MT'),
    ('Mato Grosso do Sul', 'MS'),
    ('Minas Gerais', 'MG'),
    ('Pará', 'PA'),
    ('Paraíba', 'PB'),
    ('Paraná', 'PR'),
    ('Pernambuco', 'PE'),
    ('Piauí', 'PI'),
    ('Rio de Janeiro', 'RJ'),
    ('Rio Grande do Norte', 'RN'),
    ('Rio Grande do Sul', 'RS'),
    ('Rondônia', 'RO'),
    ('Roraima', 'RR'),
    ('Santa Catarina', 'SC'),
    ('São Paulo', 'SP'),
    ('Sergipe', 'SE'),
    ('Tocantins', 'TO');

INSERT INTO contract_type (contract)
VALUES
	('fixed_salary'),
	('per_consultation');

INSERT INTO speciality (speciality_name)
VALUES
    ('Alergia e Imunologia'),
    ('Anestesiologia'),
    ('Angiologia'),
    ('Cardiologia'),
    ('Cirurgia Cardiovascular'),
    ('Cirurgia Geral'),
    ('Cirurgia Pediátrica'),
    ('Cirurgia Plástica'),
    ('Cirurgia Torácica'),
    ('Cirurgia Vascular'),
    ('Clínica Médica'),
    ('Coloproctologia'),
    ('Dermatologia'),
    ('Endocrinologia e Metabologia'),
    ('Endoscopia'),
    ('Gastroenterologia'),
    ('Genética Médica'),
    ('Geriatria'),
    ('Ginecologia e Obstetrícia'),
    ('Hematologia e Hemoterapia'),
    ('Homeopatia'),
    ('Infectologia'),
    ('Mastologia'),
    ('Medicina de Emergência'),
    ('Medicina de Família e Comunidade'),
    ('Medicina do Trabalho'),
    ('Medicina Esportiva'),
    ('Medicina Intensiva'),
    ('Nefrologia'),
    ('Neurocirurgia'),
    ('Neurologia'),
    ('Nutrologia'),
    ('Oftalmologia'),
    ('Oncologia Clínica'),
    ('Ortopedia e Traumatologia'),
    ('Otorrinolaringologia'),
    ('Patologia'),
    ('Pediatria'),
    ('Pneumologia'),
    ('Psiquiatria'),
    ('Radiologia e Diagnóstico por Imagem'),
    ('Reumatologia'),
    ('Urologia');

INSERT INTO measure (measure_unit)
VALUES
    ('mg'),
    ('g'),
    ('mcg'),
    ('ng'),
    ('mL'),
    ('L'),
    ('UI'),
    ('UI/mL'),
    ('mg/mL'),
    ('mg/g'),
    ('mcg/mL'),
    ('g/L'),
    ('mg/L'),
    ('mEq'),
    ('mEq/L'),
    ('mmol'),
    ('mmol/L'),
    ('%');

INSERT INTO medicine (measure_id, medicine_name)
VALUES
    (1, 'Paracetamol'),
    (1, 'Dipirona'),
    (1, 'Ibuprofeno'),
    (1, 'Amoxicilina'),
    (1, 'Azitromicina'),
    (1, 'Nimesulida'),
    (1, 'Diclofenaco'),
    (1, 'Cetoprofeno'),
    (1, 'Prednisona'),
    (1, 'Losartana'),
    (1, 'Enalapril'),
    (1, 'Atenolol'),
    (1, 'Anlodipino'),
    (1, 'Metformina'),
    (1, 'Omeprazol'),
    (1, 'Pantoprazol'),
    (1, 'Sinvastatina'),
    (1, 'Rosuvastatina'),
    (1, 'Clopidogrel'),
    (1, 'Ácido Acetilsalicílico'),
    (1, 'Fluoxetina'),
    (1, 'Sertralina'),
    (1, 'Escitalopram'),
    (1, 'Clonazepam'),
    (1, 'Diazepam'),
    (1, 'Loratadina'),
    (1, 'Cetirizina'),
    (1, 'Fexofenadina'),
    (3, 'Levotiroxina Sódica'),
    (3, 'Vitamina B12'),
    (8, 'Insulina Regular'),
    (8, 'Insulina NPH'),
    (8, 'Insulina Glargina'),
    (8, 'Insulina Lispro'),
    (9, 'Dipirona Gotas'),
    (9, 'Paracetamol Gotas'),
    (9, 'Ibuprofeno Suspensão Oral'),
    (9, 'Amoxicilina Suspensão Oral'),
    (10, 'Mupirocina Pomada'),
    (10, 'Gentamicina Pomada'),
    (11, 'Desmopressina Spray Nasal'),
    (14, 'Cloreto de Potássio'),
    (15, 'Solução de Cloreto de Potássio'),
    (17, 'Solução de Glicose'),
    (18, 'Hidrocortisona Creme'),
    (18, 'Cetoconazol Creme'),
    (18, 'Miconazol Creme'),
    (18, 'Peróxido de Benzoíla Gel');

